# ── Identification projet ──────────────────────────────────────────
sonar.projectKey=Lamikad0v2_CESIZen
sonar.organization=lamikad0v2
sonar.projectName=CESIZen

# ── Sources ────────────────────────────────────────────────────────
sonar.sources=frontend/src,backend/core,backend/Models,backend/Controllers

# ── Tests ──────────────────────────────────────────────────────────
sonar.tests=frontend/src/__tests__,backend/tests

# ── Exclusions ─────────────────────────────────────────────────────
sonar.exclusions=\
  **/node_modules/**,\
  **/vendor/**,\
  **/dist/**,\
  frontend/src/setupTests.js,\
  .github/**,\
  Dockerfile

# ── Coverage ───────────────────────────────────────────────────────
# JavaScript (Vitest lcov)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

#── Encodage ───────────────────────────────────────────────────────
sonar.sourceEncoding=UTF-8
