# dynamic.yml -- gere par deploy-blue-green.ps1
# Slot actif : green

http:
  routers:
    cesizen:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: cesizen-active

  services:
    cesizen-active:
      loadBalancer:
        servers:
          - url: "http://app-green:8080"

